FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY irrigation_service.py .
COPY processor.py .
COPY ingestion.py .

CMD ["python", "processor.py"]
