services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db_service
  sensor_gateway:
    build:
      context: .
      dockerfile: Dockerfile_sgw
    ports:
      - "8001:8000"
    depends_on:
      kafka:
        condition: service_healthy
  irrigation:
    build:
      context: .
      dockerfile: Dockerfile_irrigation
    depends_on:
      kafka:
        condition: service_healthy

  db_service:
    image: postgres:16-alpine
    container_name: agri_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-agriadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-agriadmin123}
      POSTGRES_DB: ${POSTGRES_DB:-agri_db}
    ports:
      - "5632:5432"
    volumes:
      - db_data:/var/lib/postgresql/data_store_1

  kafka:
    image: apache/kafka:latest
    container_name: agri-kafka
    restart: unless-stopped
    environment:
      # KRaft settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafka_data:/var/lib/kafka/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  db_data:
  kafka_data:
